### ISSUE TITLE
Not getting Token

### ISSUE THREAD

**Issue by AndyPanerai** [jessevl/homeassistant-greenchoice#2]
Hi,

I'm getting the following error while retrieving the token :

{
    "error": "invalid_clientId",
    "error_description": "ClientId should be sent."
}

I'm using Postman.

This is what i'm using as POST :

https://app.greenchoice.nl/token?grant_type=password&client_id=MobileApp&client_secret=A6E60EBF73521F57&username=*****&password=*****

**Comment by jessevl** [comment]
I'm getting the same error (although my existing token still works). I'm guessing they changed the client_id with the introduction of their new mobile app. It might be possible to sniff traffic and see what the current app uses.

**Comment by davidsuarez82** [comment]
Hi, any news about the new id we need to use?

**Comment by DanielsWrath** [comment]
Tried sniffing. However I'm new to this stuff and it seems pretty impossible to me, as they use HTTPS.

**Comment by marvandorth** [comment]
Same problem here. I'm unable to retrieve the token via the POST request.
Any help would be greatly appreciated

**Comment by jessevl** [comment]
Just tested this again and in fact the method described in the README is working again. I can get a token and successfully retrieve a list of contracts.

**Comment by marvandorth** [comment]
> Just tested this again and in fact the method described in the README is working again. I can get a token and successfully retrieve a list of contracts. Let me know if it works for you as well.

Nope, still the same output:
`{
    "error": "invalid_clientId",
    "error_description": "ClientId should be sent."
}`

**Comment by cyleo** [comment]
I tried it this morning as well, and received the same error (Postman on Mac)

**Comment by eelcohn** [comment]
I've experienced the same problem when trying to use `curl` to get the `token` and `overeenkomstid`. The problem was that the parameters weren't encoded correctly and therefore the Greenchoice API couldn't read them correctly. If you use `curl` you can try the following:
```
curl https://app.greenchoice.nl/token -X POST -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "grant_type=password" --data-urlencode "client_id=MobileApp" --data-urlencode "client_secret=A6E60EBF73521F57" --data-urlencode "username=********" --data-urlencode "password=********"
```
And to get the `overeenkomstid`:
```
curl https://app.greenchoice.nl/api/v1/klant/getovereenkomsten -X GET -H "Authorization: Bearer ********"
```

**Comment by asterixonline** [comment]
Bovenstaande werkt prima,

Is er ook mogelijkheid tot uitlezen van slimme meter? Zou graag realtime terug levering en levering willen uitlezen.

**Comment by eelcohn** [comment]
Om realtime je slimme meter uit te lezen kan je het beste de DSMR integrantie gebruiken denk ik: https://www.home-assistant.io/integrations/dsmr/

**Comment by slurpey** [comment]
I've now tried quite a lot of things to make it work - my sensor doesn't show up.
- Was able to get client ID via the post/get process
my config:
```
# in sensors.yaml
  - platform: template
    sensors:
      sun_azimuth:
        friendly_name: "Sun azimuth"
        unit_of_measurement: 'degrees'
        value_template: "{{ state_attr('sun.sun', 'azimuth') }}"
  - platform: greenchoice
    name: meterstanden
    password: !secret greenchoicepass
    username: !secret greenchoiceuser
    overeenkomst_id: !secret greenchoicecontract

#in secrets.yaml
greenchoicepass: thisismypassword
greenchoiceuser: me@gmail.com
greenchoicecontract: 791265
```

Is there a delay until the sensor shows up?  I can't figure out why it's not in my entities.  
Log file shows only one thing with "greenchoice":

2020-06-19 15:12:04 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for greenchoice which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
