### ISSUE TITLE
Create sensor which shows daily data

### ISSUE THREAD

**Issue by DanielsWrath** [jessevl/homeassistant-greenchoice#24]
The current sensor is cumulative and shows me the total gas/energy used up to that point in time. It would be nice to make the plugin generate a delta sensor, which actually shows the used resources per day.

Maybe other people would like this as well?

**Comment by jessevl** [comment]
It's a good suggestion but also quite error prone as we do not get the data directly from Greenchoice. You can use the Utility Meter component for this: https://www.home-assistant.io/integrations/utility_meter/.

**Comment by DanielsWrath** [comment]
Will look into that! Probably better to use that integration, instead of creating it from scratch. Thanks.

**Comment by DanielsWrath** [comment]
As it might be useful for other people, I added the following text to my configuration.yaml file. It creates a monthly and daily sensor for both gas and energy. Takes a day to become active.

```
utility_meter:
  daily_energy:
    source: sensor.currentenergytotal
    cycle: daily
  monthly_energy:
    source: sensor.currentenergytotal
    cycle: monthly
  daily_gas:
    source: sensor.currentgas
    cycle: daily
  monthly_gas:
    source: sensor.currentgas
    cycle: monthly
```
